PYS/ZabitaWebApplication/ViewModels/NavbarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EBS.Data;

namespace ZabitaWebApplication.ViewModels
{
    public class NavbarViewModel
    {
        public List<Notification> Notifications { get; set; }

        public User user { get; set; }
    }
}

PYS/ZabitaWebApplication/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using ZabitaWebApplication.Base_Controller;
using EBS.Data;
using EBS.Extensions;
using EBS.Services.Service;

namespace ZabitaWebApplication.Controllers
{
    public class MessageController : BaseSessionController
    {
        private ModelContext db = new ModelContext();
        private UserSessionClass usc = new UserSessionClass();
        private NotificationService nfc = new NotificationService();

        // Mesajlaşılan kişileri listeler.
        public ActionResult Index(int mesajlasilanID = 0)
        {
            List<int> userIdList = new List<int>();

            int userid = Int32.Parse(Session["userId"].ToString());

            var messages = db.Message.Where(i=> i.GetUserID == userid || i.PostUserID == userid);

            foreach (var item in messages)
            {
                userIdList.Add(item.GetUserID);
                userIdList.Add(item.PostUserID);
            }
            userIdList= userIdList.Distinct().ToList();
            userIdList.Remove(userid);

            var allUsers = db.User.ToList();

            List<User> userListVm = new List<User>();
            User pivotUser;
            for (int i = 0; i < userIdList.Count; i++)
            {
                pivotUser = new User();
                pivotUser = allUsers.Where(w => w.ID == userIdList[i]).FirstOrDefault();
                if (pivotUser != null)
                {
                    userListVm.Add(pivotUser);
                }
            }
            if(mesajlasilanID == 0)
            {
                ViewBag.mesajGetir = 0;
            }else
            {
                ViewBag.mesajGetir = mesajlasilanID;
            }
            
            return View(userListVm);
        }

        // Son 20 mesaj bilgisini döndürür.
        public PartialViewResult Details(int? id)
        {
            if (id == 0)
            {
                ViewBag.partialVeri = "Mesajlaşmak için kişi seçin!";
                return PartialView("BosView");
            }
            ViewBag.karsiID = id;
            int userid = Int32.Parse(Session["userId"].ToString());

            var messages = db.Message.Where(i => (i.GetUserID == userid || i.PostUserID == userid) && (i.GetUserID == id || i.PostUserID == id)).OrderBy(i=>i.Date).Take(20).ToList();
            return PartialView(messages);
        }

        //Mesaj oluşturur.
        [HttpPost]
        public ActionResult Create(string yorumyap, string idDonucu)
        {
            try
            {
                string username = Session["username"].ToString();
                var kullanici = db.User.FirstOrDefault(i => i.Username == username);

                Message mesaj = new Message();
                int aid = Int32.Parse(idDonucu);

                mesaj.PostUserID = kullanici.ID;
                mesaj.GetUserID = aid;
                mesaj.MessageContent = yorumyap;
                mesaj.Date = DateTime.Now;

                db.Message.Add(mesaj);
                db.SaveChanges();

                nfc.Create(kullanici.Username + " kişisinden size "+mesaj.MessageContent + " yazdı.",aid);
                return RedirectToAction("Index", new { mesajlasilanID = idDonucu });
            }
            catch
            {
                return RedirectToAction("Index", new { mesajlasilanID = idDonucu });
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PYS/ZabitaWebApplication/Controllers/RoleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ZabitaWebApplication.Base_Controller;
using EBS.Data;
using ZabitaWebApplication.ViewModels;
using EBS.Extensions;
using EBS.Services.Service;
using EBS.Data.Result;

namespace ZabitaWebApplication.Controllers
{
    public class RoleController : BaseSessionController
    {
        private ModelContext db = new ModelContext();
        private UserSessionClass usc;
        private NotificationService nfc;
        private RoleService _roleService;

        public RoleController()
        {
            usc = new UserSessionClass();
            nfc = new NotificationService();
            _roleService = new RoleService();
        }

        // Tüm rolleri listeler
        public ActionResult Index()
        {
            Result<List<Role>> result = _roleService.GetAll();
            if (!result.IsSuccess)
            {
                return RedirectToAction("Home", "ErrorPage", new { error = result.Message });
            }
            return View(result.Data);
        }

        // Rolün yetkilerini sıralar.
        public ActionResult Details(int id)
        {
            var result = _roleService.GetByID(id);
            if (!result.IsSuccess)
            {
                return RedirectToAction("Home", "ErrorPage", new { error = result.Message });
            }
            return View(result.Data.Auth.ToList());
        }

        // Rol oluşturmaya yarar.
        public ActionResult Create()
        {
            string username = Session["username"].ToString();
            var kullanici = db.User.Where(i => i.Username == username).SingleOrDefault();

            if (!usc.YetkiKontrol(kullanici,UserSessionClass.Yetkiler.Rol_Olusturabilir))
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Bu işlem için gerekli yetkiniz bulunmamaktadır!" });
            }

            List<CheckBoxModel> cbm = new List<CheckBoxModel>();
            foreach (var i in db.Auth.ToList())
            {
                cbm.Add(new CheckBoxModel { Checked = false, ID = i.ID, Name = i.Name });
            }
            Rol_SubRol_ViewModel rsv = new Rol_SubRol_ViewModel() { SubList = cbm };
            return View(rsv);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Rol_SubRol_ViewModel cbm)
        {
            try
            {
                Role rol = new Role();
                rol.Name = cbm.RolAd;

                foreach (var i in cbm.SubList)
                {
                    if (i.Checked)
                    {
                        rol.Auth.Add(db.Auth.Where(k => k.ID == i.ID).SingleOrDefault());
                    }
                }

                if (rol.Name == "Default")
                {
                    return RedirectToAction("ErrorPage", "Home", new { error = "Bu İsimde Bir Rol Oluşturamazsınız!" });
                }
                db.Role.Add(rol);
                db.SaveChanges();

                usc.CreateActionLog(Session["userId"].ToString(), cbm.RolAd.ToString(), " adlı rolü ekledi.");
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Hay Aksi!" });
            }
        }
        
        //Rol güncellemeyi sağlar.
        public ActionResult Edit(int? id)
        {
            string username = Session["username"].ToString();
            var kullanici = db.User.Where(i => i.Username == username).SingleOrDefault();

            if (!usc.YetkiKontrol(kullanici, UserSessionClass.Yetkiler.Rol_Guncelleyebilir))
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Bu işlem için gerekli yetkiniz bulunmamaktadır!" });
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role rol = db.Role.Find(id);
            if (rol == null)
            {
                return HttpNotFound();
            }
            if (rol.Name == "Default")
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Bu Rolü Değiştirme Yetkiniz Bulunmamaktadır!" });
            }

            List<CheckBoxModel> cbm = new List<CheckBoxModel>();

            bool a = false;
            foreach (var i in db.Auth.ToList())
            {
                foreach (var k in rol.Auth.ToList())
                {
                    if (i == k)
                    {
                        cbm.Add(new CheckBoxModel { Checked = true, ID = i.ID, Name = i.Name });
                        a = true;
                        break;
                    }
                }
                if (!a)
                    cbm.Add(new CheckBoxModel { Checked = false, ID = i.ID, Name = i.Name });
                a = false;
            }
            Rol_SubRol_ViewModel rsv = new Rol_SubRol_ViewModel() { SubList = cbm };
            rsv.RolAd = rol.Name;
            return View(rsv);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Rol_SubRol_ViewModel model)
        {
            List<Auth> authList = new List<Auth>();
            try
            {
                var rol = db.Role.Where(i => i.ID == id).SingleOrDefault();

                foreach (var i in rol.Auth.ToList())
                {
                    rol.Auth.Remove(i);
                }

                foreach (var i in model.SubList)
                {
                    if (i.Checked)
                    {
                        rol.Auth.Add(db.Auth.Where(k => k.ID == i.ID).SingleOrDefault());
                    }
                }
                rol.Name = model.RolAd;

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Hay Aksi!" });
            }

        }

        // Rol silmeyi sağlar.
        public ActionResult Delete(int? id)
        {

            string username = Session["username"].ToString();
            var kullanici = db.User.Where(i => i.Username == username).SingleOrDefault();

            if (!usc.YetkiKontrol(kullanici, UserSessionClass.Yetkiler.Rol_Silebilir))
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Bu işlem için gerekli yetkiniz bulunmamaktadır!" });
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role rol = db.Role.Find(id);
            if (rol == null)
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Rol Bulunamadı!" });
            }
            if (rol.Name == "Default")
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Bu Rolü Silme Yetkiniz Bulunmamaktadır!" });
            }
            return View(rol);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Role rol = db.Role.Find(id);
                foreach (var i in rol.Auth.ToList())
                {
                    rol.Auth.Remove(i);
                }

                var defaultRol = db.Role.Where(i => i.Name == "Default").SingleOrDefault();
                foreach (var i in rol.User.ToList())
                {
                    i.Role = defaultRol;
                }
                db.Role.Remove(rol);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Hay Aksi!" });
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PYS/ZabitaWebApplication/Views/PartialViews/Navbar.cshtml
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">

                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">

                        <img src="~/Content/ProfilResimler/@Session["userPic"].ToString()" alt="">@Session["username"].ToString()
                        <span class="fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="@Url.Action("Profil","User")"> Profilim</a></li>
                        <li>
                            <a href="@Url.Action("Index","Message")">
                                <span>Mesajlar</span>
                            </a>
                        </li>
                        <li><a href="@Url.Action("YetkileriniGoruntule","User")">Yetkilerim</a></li>
                        <li><a href="@Url.Action("Logout","Home")"><i class="fa fa-sign-out pull-right"></i> Çıkış Yap</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>

PYS/ZabitaWebApplication/Views/PartialViews/Sidebar.cshtml
<div class="col-md-3 left_col" style="background-color: transparent;">
    <div class="left_col scroll-view" style="background-color: transparent;">
        <div class="navbar nav_title text-center" style="border: 0;padding-bottom:15px;">
            <a href="@Url.Action("Index","User")" class="site_title" style="color:#ff9c03 !important"><h5>E-Bird PYS</h5></a>
            <hr style="border-color:#ff9c03 !important;background-color:#ff9c03 !important" />
            <div class="clearfix"></div>

        </div>
        <div class="clearfix"></div>
        <!-- menu profile quick info -->
        <div class="profile" style="padding-top:10px;">
            <div class="profile_pic">
                <img src="~/Content/ProfilResimler/@Session["userPic"].ToString()" class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Hoşgeldiniz,</span>
                @if (Session["username"] != null)
                {
                    <h2 style="color:#ff9c03 !important">@Session["username"]</h2>
                }
                else
                {
                    <h2 style="color:#ff9c03 !important">Misafir</h2>
                }
            </div>
        </div>
        <!-- /menu profile quick info -->
        <br />
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3 style="color:#ff9c03 !important">Menu</h3>
                <ul class="nav side-menu">
                    <li>
                        <a style="color:#ff9c03 !important" href="@Url.Action("Index","Project")"><i class="fa fa-home"></i> Projelerim </a>
                    </li>
                    <li>
                        <a style="color:#ff9c03 !important" href="@Url.Action("Gorevlerim","User")"><i class="fa fa-ambulance"></i> Görevlerim</a>
                    </li>
                    <li>
                        <a style="color:#ff9c03 !important" data-toggle="dropdown" aria-expanded="false"><i style="color:#ff9c03 !important" class="fa fa-desktop"></i>Hızlı Menü<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a style="color:#ff9c03 !important" href="@Url.Action("Create","Project")">Proje Oluştur</a></li>
                            <li><a style="color:#ff9c03 !important" href="@Url.Action("Index","Message")">Mesajlar</a></li>
                        </ul>
                    </li>
                    <li>
                        <a style="color:#ff9c03 !important" data-toggle="dropdown" aria-expanded="false"><i style="color:#ff9c03 !important" class="fa fa-archive"></i>Rol<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a style="color:#ff9c03 !important" href="@Url.Action("Create","Role")">Rol Ekle</a></li>
                            <li><a style="color:#ff9c03 !important" href="@Url.Action("Index","Role")">Rol Listesi</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>