PYS/ZabitaWebApplication/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using ZabitaWebApplication.Base_Controller;
using EBS.Data;
using ZabitaWebApplication.ViewModels;
using EBS.Extensions;
using EBS.Services.Service;

namespace ZabitaWebApplication.Controllers
{
    public class IssueController : BaseSessionController
    {
        private ModelContext db = new ModelContext();
        private UserSessionClass usc = new UserSessionClass();
        private NotificationService nfc = new NotificationService();

        //Görevi detaylıca verir.
        public PartialViewResult Details(int? id)
        {
            if (id == 0)
            {
                ViewBag.partialVeri = "Görev Bulunmamaktadır!";
                return PartialView("BosView");
            }
            IssueDetailViewModel vm = new IssueDetailViewModel();
            vm.issue = db.Issue.Find(id);
            vm.status = db.Status.ToList();
            return PartialView(vm);
        }

        //Alt görev oluştururken kullanılır.
        public ActionResult Create(int projeId, int issueId)
        {
            try
            {
                string username = Session["username"].ToString();
                var kullanici = db.User.Where(i => i.Username == username).SingleOrDefault();

                if (usc.YetkiKontrol(kullanici, UserSessionClass.Yetkiler.Gorev_Olusturabilir))
                {

                    var proje = kullanici.Project1.SingleOrDefault(i => i.ID == projeId);
                    if (proje == null)
                    {
                        return RedirectToAction("ErrorPage", "Home", new { error = "Bu işlem için gerekli yetkiniz bulunmamaktadır!" });
                    }
                    ViewBag.PriorityID = new SelectList(db.Priority, "ID", "Name");
                    return PartialView("CreateModal");
                }
                return RedirectToAction("ErrorPage", "Home", new { error = "Bu işlem için gerekli yetkiniz bulunmamaktadır!" });
            }
            catch
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Hata!" });
            }
        }

        [HttpPost]
        public ActionResult Create(int projeId, int issueId, Issue issue)
        {
            try
            {
                issue.isSubTask = true;
                issue.Issue2.Add(db.Issue.FirstOrDefault(i => i.ID == issueId));
                int userid = Int32.Parse(Session["userId"].ToString());
                issue.ProjectID = projeId;
                issue.CreatedDate = DateTime.Now;
                issue.StatusID = db.Status.First().ID;
                db.Issue.Add(issue);
                db.SaveChanges();
                usc.CreateActionLog(Session["userId"].ToString(), issueId.ToString(), "issue ekledi");
                return RedirectToAction("Details", "Project", new { id = projeId, issueId = issue.ID });
            }
            catch
            {
                ViewBag.PriorityID = new SelectList(db.Priority, "ID", "Name", issue.PriorityID);
                return View(issue);
            }
        }

        //Ana görev oluştururken kullanılır.
        public PartialViewResult CreateModal(int projeId, int issueId = 0)
        {
            try
            {
                string username = Session["username"].ToString();
                var kullanici = db.User.Where(i => i.Username == username).SingleOrDefault();

                if (usc.YetkiKontrol(kullanici, UserSessionClass.Yetkiler.Gorev_Olusturabilir))
                {

                    var proje = kullanici.Project1.SingleOrDefault(i => i.ID == projeId);
                    if (proje == null)
                    {
                        ViewBag.partialVeri = "Bulunmadığınız projeye görev ekleyemezsiniz!";
                        return PartialView("BosView");
                    }
                    ViewBag.PriorityID = new SelectList(db.Priority, "ID", "Name");
                    return PartialView();
                }
                ViewBag.partialVeri = "Yetkiniz Bulunmamaktadır!";
                return PartialView("BosView");
            }
            catch
            {
                ViewBag.partialVeri = "Hata Oldu!";
                return PartialView("BosView");
            }
        }

        [HttpPost]
        public ActionResult CreateModal(int projeId, int issueId, Issue issue)
        {
            try
            {
                if (issueId != 0)
                {
                    issue.isSubTask = true;
                    issue.Issue2.Add(db.Issue.FirstOrDefault(i => i.ID == issueId));
                    int userid = Int32.Parse(Session["userId"].ToString());
                    issue.ProjectID = projeId;
                    issue.CreatedDate = DateTime.Now;
                    issue.StatusID = db.Status.First().ID;
                    db.Issue.Add(issue);
                    db.SaveChanges();
                    usc.CreateActionLog(Session["userId"].ToString(), issueId.ToString(), "issue ekledi");
                }
                else
                {
                    issue.isSubTask = false;
                    int userid = Int32.Parse(Session["userId"].ToString());
                    issue.ProjectID = projeId;
                    issue.CreatedDate = DateTime.Now;
                    issue.StatusID = db.Status.First().ID;
                    db.Issue.Add(issue);
                    db.SaveChanges();
                    usc.CreateActionLog(Session["userId"].ToString(), issue.Name, " görevini oluşturdu. ");
                }
            }
            catch
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Bu işlem için gerekli yetkiniz bulunmamaktadır!" });
            }
            return RedirectToAction("Details", "Project", new { id = projeId, issueID = issue.ID });
        }

        //Görev güncellemek için kullanılır.
        public ActionResult Edit(int id, int projeId)
        {
            try
            {
                string username = Session["username"].ToString();
                var kullanici = db.User.Where(i => i.Username == username).SingleOrDefault();

                if (usc.YetkiKontrol(kullanici, UserSessionClass.Yetkiler.Gorev_Guncelleyebilir))
                {
                    /*var sorgu = (from gorevler in db.Issues join projeler in db.Projects on gorevler.ProjectID equals projeler.ID where gorevler.ProjectID==projeId select new { gorevler,projeler }).ToList();

                    var x = (from q in sorgu where q.projeler.Users.Contains(kullanici)select new {q}).ToList();*/
                    var proje = kullanici.Project1.SingleOrDefault(i => i.ID == projeId);
                    if (proje == null)
                    {
                        return RedirectToAction("ErrorPage", "Home", new { error = "Bulunmadığınız projeye görev ekleyemezsiniz!" });
                    }
                    var gorev = proje.Issue.SingleOrDefault(i => i.ID == id);
                    if (gorev == null)
                    {
                        return RedirectToAction("ErrorPage", "Home", new { error = "Bulunmadığınız projeye görev ekleyemezsiniz!" });
                    }
                    ViewBag.PriorityID = new SelectList(db.Priority, "ID", "Name");
                    ViewBag.StatusID = new SelectList(db.Status, "ID", "Name");
                    return View(gorev);
                }
                return RedirectToAction("ErrorPage", "Home", new { error = "Bu işlem için gerekli yetkiniz bulunmamaktadır!" });
            }
            catch
            {
                return RedirectToAction("ErrorPage", "Home", new { error = "Bir Hata Oldu!" });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, int projeId, Issue model)
        {
            try
            {
                var gorev = db.Issue.SingleOrDefault(i => i.ID == id);
                gorev.Name = model.Name;
                gorev.Description = model.Description;
                gorev.PriorityID = model.PriorityID;
                gorev.StatusID = model.StatusID;
                db.SaveChanges();
                usc.UpdateActionLog(Session["userId"].ToString(), gorev.ID.ToString(), " görevi güncelledi ");
                return RedirectToAction("Details", "Product", new { id = projeId, issueID = id });
            }
            catch
            {
                ViewBag.PriorityID = new SelectList(db.Priority, "ID", "Name", model.PriorityID);
                ViewBag.Status = new SelectList(db.Status, "ID", "Name");
                return View(model);
            }

        }

        //Yorum oluşturmak için kullanılır.
        [HttpPost]
        public ActionResult YorumYap(string yorumyap, string idDonucu)
        {
            try
            {
                string username = Session["username"].ToString();
                var kullanici = db.User.FirstOrDefault(i => i.Username == username);
                int id = Int32.Parse(idDonucu);

                Comment yorum = new Comment();
                var gorev = db.Issue.FirstOrDefault(i => i.ID == id);

                yorum.UserID = kullanici.ID;
                yorum.IssueID = gorev.ID;
                yorum.Description = yorumyap;
                yorum.Date = DateTime.Now;

                db.Comment.Add(yorum);
                db.SaveChanges();

                usc.CreateActionLog(kullanici.ID.ToString(), gorev.ID.ToString(), "göreve yorum yaptı. ");
                return RedirectToAction("Details", "Project", new { id = gorev.ProjectID, issueID = idDonucu });
            }
            catch
            {
                return RedirectToAction("Detay", new { id = idDonucu });
            }

        }

        //Yorum güncellemek için kullanılır.
        public ActionResult YorumGuncelle(int id)
        {
            try
            {

PYS/ZabitaWebApplication/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using ZabitaWebApplication.Base_Controller;
using EBS.Data;
using EBS.Extensions;
using EBS.Services.Service;

namespace ZabitaWebApplication.Controllers
{
    public class MessageController : BaseSessionController
    {
        private ModelContext db = new ModelContext();
        private UserSessionClass usc = new UserSessionClass();
        private NotificationService nfc = new NotificationService();

        // Mesajlaşılan kişileri listeler.
        public ActionResult Index(int mesajlasilanID = 0)
        {
            List<int> userIdList = new List<int>();

            int userid = Int32.Parse(Session["userId"].ToString());

            var messages = db.Message.Where(i=> i.GetUserID == userid || i.PostUserID == userid);

            foreach (var item in messages)
            {
                userIdList.Add(item.GetUserID);
                userIdList.Add(item.PostUserID);
            }
            userIdList= userIdList.Distinct().ToList();
            userIdList.Remove(userid);

            var allUsers = db.User.ToList();

            List<User> userListVm = new List<User>();
            User pivotUser;
            for (int i = 0; i < userIdList.Count; i++)
            {
                pivotUser = new User();
                pivotUser = allUsers.Where(w => w.ID == userIdList[i]).FirstOrDefault();
                if (pivotUser != null)
                {
                    userListVm.Add(pivotUser);
                }
            }
            if(mesajlasilanID == 0)
            {
                ViewBag.mesajGetir = 0;
            }else
            {
                ViewBag.mesajGetir = mesajlasilanID;
            }
            
            return View(userListVm);
        }

        // Son 20 mesaj bilgisini döndürür.
        public PartialViewResult Details(int? id)
        {
            if (id == 0)
            {
                ViewBag.partialVeri = "Mesajlaşmak için kişi seçin!";
                return PartialView("BosView");
            }
            ViewBag.karsiID = id;
            int userid = Int32.Parse(Session["userId"].ToString());

            var messages = db.Message.Where(i => (i.GetUserID == userid || i.PostUserID == userid) && (i.GetUserID == id || i.PostUserID == id)).OrderBy(i=>i.Date).Take(20).ToList();
            return PartialView(messages);
        }

        //Mesaj oluşturur.
        [HttpPost]
        public ActionResult Create(string yorumyap, string idDonucu)
        {
            try
            {
                string username = Session["username"].ToString();
                var kullanici = db.User.FirstOrDefault(i => i.Username == username);

                Message mesaj = new Message();
                int aid = Int32.Parse(idDonucu);

                mesaj.PostUserID = kullanici.ID;
                mesaj.GetUserID = aid;
                mesaj.MessageContent = yorumyap;
                mesaj.Date = DateTime.Now;

                db.Message.Add(mesaj);
                db.SaveChanges();

                nfc.Create(kullanici.Username + " kişisinden size "+mesaj.MessageContent + " yazdı.",aid);
                return RedirectToAction("Index", new { mesajlasilanID = idDonucu });
            }
            catch
            {
                return RedirectToAction("Index", new { mesajlasilanID = idDonucu });
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PYS/ZabitaWebApplication/Views/Issue/Delete.cshtml
@model EBS.Data.Issue

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="col-md-4 col-md-offset-4 panel panel-danger">
    <h2>@Model.Name Isimli Görevi</h2>

    <h3>Silmek istediğine emin misin?</h3>
    <div>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Sil" class="btn btn-red" />
            </div>
        }
    </div>
</div>

PYS/ZabitaWebApplication/Views/Issue/Details.cshtml
@model ZabitaWebApplication.ViewModels.IssueDetailViewModel
<div class="container w3-sand">
    <div class="col-lg-12">
        <div class="panel panel-@Model.issue.Priority.Symbol col-lg-12 col-md-10 " style="padding-top:10px;">
            <div class="panel-heading col-lg-12 col-md-10 "> @Model.issue.Name</div>
            <br />
            <div>
                <div class="text-center">
                    <br />
                    @if (Model.issue.isSubTask)
                    {
                        <h4 class="control-label text-success">Alt Görev</h4>
                    }
                    else
                    {
                        <h4 class="control-label text-primary">Ana Görev</h4>
                    }
                </div>
                @if (Session["userId"].ToString() == Model.issue.ReporterID.ToString())
                {
                    <div class="text-center ">
                        @foreach (var i in Model.status)
                        {
                            @Html.ActionLink(i.Name, "GorevDurumDegis", new { id = Model.issue.ID, statusID = i.ID }, new { @class = "w3-button w3-indigo" })<shadow></shadow>
                        }
                    </div>
                }
                <br />
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        <strong class="control-label col-md-2">Görev Önceliği</strong>
                    </dt>
                    <dd>
                        <span class="label label-@Model.issue.Priority.Symbol">
                            @Html.DisplayFor(model => model.issue.Priority.Name)
                        </span>
                    </dd>
                    <dt>
                        <strong class="control-label col-md-2">Görev Adı</strong>
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.issue.Name)
                    </dd>
                    <dt>
                        <strong class="control-label col-md-2">Görev Statüsü</strong>
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.issue.Status.Name)
                    </dd>
                    <dt>
                        <strong class="control-label col-md-2">Görev Çalışanı</strong>
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.issue.User.Name)
                    </dd>
                    <dt>
                        <strong class="control-label col-md-2">Görev Açıklaması</strong>
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.issue.Description)
                    </dd>
                    <dt>
                        <strong class="control-label col-md-2">Görev Oluşturma Tarihi</strong>
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.issue.CreatedDate)
                    </dd>
                    <dt>
                        <strong class="control-label col-md-2">Görev Bitiş Tarihi</strong>
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.issue.LastDate)
                    </dd>
                    <dt>
                        <strong class="control-label col-md-2">Görev Dosyaları</strong>
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.issue.FileString)
                    </dd>
                </dl>
            </div>
            <p class="text-center">
                @if (Model.issue.ReporterID == null)
                {
                    @Html.ActionLink("Üstlen", "GorevTalipOl", new { id = Model.issue.ID }, new { @class = "w3-button w3-green" })
                    <button type="button" id="kayit" onclick="GorevAta()" class="w3-button w3-lime" style="margin-top:3px">Görev Ata</button>
                }

                else if (Model.issue.User.Username == Session["username"].ToString())
                {
                    <div class="text-center">
                        @Html.ActionLink("İptal Et", "GorevIptalEt", new { id = Model.issue.ID }, new { @class = "w3-button w3-red" })
                    </div>
                }
                <div class="text-right">
                    @Html.ActionLink("Güncelle", "Edit", new { id = Model.issue.ID, projeId = Model.issue.ProjectID }, new { @class = "w3-button w3-orange" })
                    @Html.ActionLink("Sil", "Delete", new { id = Model.issue.ID }, new { @class = "w3-button w3-red" })
                    <button class="w3-button w3-black" type="button" id="altgorevekle">Alt Görev</button>
                </div>
            </p>

        </div>
        <div class="panel panel-info col-lg-12 col-md-6 col-xs-4" style="padding-top:10px;">
            <div class="panel-heading panel-@Model.issue.Priority.Symbol col-lg-12 col-md-10 "> Alt Görevler</div>
            <div class="col-lg-12 col-md-10 ">
                <table class="table table-hover">
                    <tr></tr>
                    @foreach (var item in Model.issue.Issue1)
                    {
                        <tr style="color:blue;">
                            <td>
                                @Html.ActionLink(item.Name, "AltGorevGetir", new { id = item.ProjectID, issueId = item.ID })
                            </td>
                            <td>
                                @Html.ActionLink(item.Priority.Name, "AltGorevGetir", new { id = item.ProjectID, issueId = item.ID })
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status.Name)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
        <div class="panel panel-info col-lg-12 col-md-6 col-xs-4" style="padding-top:10px;">
            <div class="col-lg-12 col-md-10 ">
                @using (Html.BeginForm("YorumYap", "Issue", FormMethod.Post))
                {
                    <h4>Yorumlar</h4>
                    <div>
                        <textarea class="form-control" rows="3" name="yorumyap"></textarea>
                        <br />
                        <input class="form-control" name="idDonucu" style="visibility: hidden" value="@Model.issue.ID" />
                        <input type="submit" value="Yorum Yap" class="w3-button w3-lime col-sm-offset-10" />
                    </div>
                }
                <hr />
                <div class="container col-lg-12 col-md-10 ">
                    @foreach (var i in Model.issue.Comment.Take(10).Reverse())
                    {
                        <div class="card">
                            <div class="card-header">
                                <div class="w3-sand"><h4>@i.User.Name <span class="glyphicon glyphicon-arrow-down"></span></h4></div>
                            </div>
                            <div class="card-block ">
                                <hr />
                                <h4 class="card-title text-center">@i.Description</h4>
                                <p class="card-text text-center">@i.Date.ToShortDateString() & @i.Date.ToShortTimeString()</p>
                                @if (i.User.Username != Session["username"].ToString())
                                {
                                    <div class="text-right"><a href="@Url.Action("Index","Message",new { mesajlasilanID = i.UserID })" class="w3-button w3-orange ">Mesaj At</a></div>
                                }
                                else
                                {
                                    <p>
                                        @Html.ActionLink("Güncelle", "YorumGuncelle", new { id = i.ID }, new { @class = "w3-button w3-orange" }) <shadow></shadow>
                                        @Html.ActionLink("Sil", "YorumSil", new { id = i.ID }, new { @class = "w3-button w3-red" })
                                    </p>
                                }
                            </div>
                        </div>
                        <hr />
                        <br />
                    }
                </div>
            </div>
        </div>
        <div class="modal fade" tabindex="-1" role="dialog" id="kayitFormu">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Görev Atama Listesi</h4>
                    </div>
                    <div id="deneme" class="modal-body">
                        @{
                            Html.RenderAction("GorevAta", "Issue", new { id = Model.issue.ID });
                        }
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Kapat</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#kayit').click(function () {
        $("#kayitFormu").modal("show");

    });
    $('#altgorevekle').click(function () {
        $("#ekleFormu").modal("show");
        $("#modal_body").load('/Issue/CreateModal?projeId=@Model.issue.ProjectID&&issueId=@Model.issue.ID');
    });
</script>
<style>
    .btn {
        background-color: dodgerblue;
        border-color: gray;
        color: white;
        -webkit-transition-duration: 0.4s; /* Safari */
        position: relative;
        text-decoration: none;
        overflow: hidden;
        cursor: pointer;
        height: 30px;
    }

        .btn:hover {
            background-color: white !important; /* Green */
            color: dodgerblue !important;
            -webkit-transition-duration: 0.4s; /* Safari */
        }
</style>

PYS/ZabitaWebApplication/Views/Issue/GorevAta.cshtml
@model IEnumerable<EBS.Data.User>

@*@{
    ViewBag.Title = "GorevAta";
    //Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}*@

<h2>Kişi Seç</h2>

<table class="table table-hover">
    <tr>
        <th>
            Adı
        </th>
        <th>
            Soyadı
        </th>
        <th>
            Mail Adresi
        </th>
        <th>
            Rolü
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="tr" style="cursor:pointer">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role.Name)
            </td>
            <td>
                @Html.ActionLink("Seç", "GorevAtaConfirmed", new { id = item.ID , issueId = ViewBag.gorevID },new { @class="btn" })
            </td>
        </tr>
    }

</table>

PYS/ZabitaWebApplication/Views/Issue/PartialDetails.cshtml
@model EBS.Data.Issue

<div class="panel panel-@Model.Priority.Symbol col-lg-12 col-md-10 " style="padding-top:10px;">

    <div class="panel-heading col-lg-12 col-md-10 "> @Model.Priority.Name</div>
    <div>

        @if (Model.isSubTask)
        {
            <h4 class="control-label col-md-2 text-success">Alt Görev</h4>
        }
        else
        {
            <h4 class="control-label col-md-2 text-primary">Ana Görev</h4>
        }
        <hr />
        <dl class="dl-horizontal">
            <dt>
                <strong class="control-label col-md-2">Görev Önceliği</strong>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Priority.Name)
            </dd>

            <dt>
                <strong class="control-label col-md-2">Proje Adı</strong>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Project.Name)
            </dd>

            <dt>
                <strong class="control-label col-md-2">Görev Statüsü</strong>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status.Name)
            </dd>

            <dt>
                <strong class="control-label col-md-2">Görev Çalışanı</strong>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.Name)
            </dd>

            <dt>
                <strong class="control-label col-md-2">Görev Adı</strong>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                <strong class="control-label col-md-2">Görev Açıklaması</strong>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                <strong class="control-label col-md-2">Görev Oluşturma Tarihi</strong>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>

            <dt>
                <strong class="control-label col-md-2">Görev Dosyaları</strong>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FileString)
            </dd>

        </dl>
    </div>
    <p>
        @if (Model.ReporterID == null)
        {
            @Html.ActionLink("Göreve Talip Ol", "GorevTalipOl", new { id = Model.ID }, new { @class = "btn" })
        }
        else if (Model.User.Username == Session["username"].ToString())
        {
            @Html.ActionLink("Görevi İptal Et", "GorevIptalEt", new { id = Model.ID }, new { @class = "btn" })
        } |
        @Html.ActionLink("Güncelle", "Edit", new { id = Model.ID, projeId = Model.ProjectID }, new { @class = "btn" }) |
        @Html.ActionLink("Alt Görev Ekle", "Create", new { issueId = Model.ID, projeId = Model.ProjectID }, new { @class = "btn" })
    </p>


</div>

<div class="panel panel-info col-lg-12 col-md-6 col-xs-4" style="padding-top:10px;">

    <div class="panel-heading panel-@Model.Priority.Symbol col-lg-12 col-md-10 "> Alt Görevler</div>
    <div class="col-lg-12 col-md-10 ">
        <table class="table table-hover">
            <tr></tr>
            @foreach (var item in Model.AltGorevs)
            {
                <tr style="color:blue;" onclick="@Url.Action("Detay","Issue", new { id = item.ID })">
                    <td>
                        asd
                    </td>
                    <td>
                        asd
                    </td>
                    <td>
                        @Html.ActionLink(item.Name, "Detay", new { id = item.ID })
                        @Html.ActionLink(item.Priority.Name, "Detay", new { id = item.ID })
                        @Html.DisplayFor(modelItem => item.Status.Name)
                    </td>
                </tr>
            }
        </table>
    </div>

    <div class="col-lg-12 col-md-10 ">

        @using (Html.BeginForm("YorumYap", "Issue", FormMethod.Post))
        {
            <h4>Yorumlar</h4>
            <div>
                <textarea class="form-control" rows="3" name="yorumyap"></textarea>
                <br />
                <input class="form-control" name="idDonucu" style="visibility: hidden" value="@Model.ID" />
                <input type="submit" value="Yorum Yap" class="btn btn-info col-sm-offset-10" />
            </div>
        }
        <hr />

        <div class="container col-lg-12 col-md-10 ">
            @foreach (var i in Model.Comments.Take(15).Reverse())
            {
                <div class="card">
                    <div class="card-header">
                        @i.User.Name
                    </div>
                    <div class="card-block ">
                        <h4 class="card-title">@i.Description</h4>
                        <p class="card-text">@i.Date</p>
                        @if (i.User.Username != Session["username"].ToString())
                        {
                            <a href="@Url.Action("Details","Message",new { id = i.UserID })" class="btn btn-info">Mesaj At</a>
                        }
                        else
                        {
                            <p>
                                @Html.ActionLink("Güncelle", "YorumGuncelle", new { id = i.ID }, new { @class = "btn" }) |
                                @Html.ActionLink("Sil", "YorumSil", new { id = i.ID }, new { @class = "btn" })
                            </p>
                        }
                    </div>
                </div>
                <hr />
                <br />
            }
        </div>
    </div>
</div>
<style>
    .btn {
        background-color: dodgerblue;
        border-color: gray;
        color: white;
        -webkit-transition-duration: 0.4s; /* Safari */
        position: relative;
        text-decoration: none;
        overflow: hidden;
        cursor: pointer;
        height: 30px;
    }

        .btn:hover {
            background-color: white !important; /* Green */
            color: dodgerblue !important;
            -webkit-transition-duration: 0.4s; /* Safari */
        }
</style>